services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  PixelCoda\TextFlow\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  PixelCoda\TextFlow\Controller\TextFlowController:
    public: true
    tags: ['backend.controller']

  PixelCoda\TextFlow\Service\TextFlowService:
    public: true

  PixelCoda\TextFlow\Command\ImportPatternsCommand:
    tags:
      - name: 'console.command'
        command: 'textflow:import-patterns'
        description: 'Imports additional language patterns for TextFlow'
