<?php
return [
    'de' => [
        // Deutsche Trennungsmuster
        ['pattern' => 'sch'],
        ['pattern' => 'ch'],
        ['pattern' => 'ck'],
        ['pattern' => 'tz'],
        ['pattern' => 'tsch'],
        ['pattern' => 'ver'],
        ['pattern' => 'be'],
        ['pattern' => 'ge'],
        ['pattern' => 'un'],
        ['pattern' => 'er'],
        ['pattern' => 'ent'],
        ['pattern' => 'emp'],
        ['pattern' => 'ung'],
        ['pattern' => 'lich'],
        ['pattern' => 'isch'],
        ['pattern' => 'ig'],
    ],
    'en' => [
        // Englische Trennungsmuster
        ['pattern' => 'th'],
        ['pattern' => 'ch'],
        ['pattern' => 'sh'],
        ['pattern' => 'ing'],
        ['pattern' => 'tion'],
        ['pattern' => 'pre'],
        ['pattern' => 'post'],
        ['pattern' => 'un'],
        ['pattern' => 're'],
        ['pattern' => 'dis'],
        ['pattern' => 'able'],
        ['pattern' => 'ment'],
    ],
    'fr' => [
        // Französische Trennungsmuster
        ['pattern' => 'ch'],
        ['pattern' => 'ph'],
        ['pattern' => 'gn'],
        ['pattern' => 'tion'],
        ['pattern' => 'pre'],
        ['pattern' => 'de'],
        ['pattern' => 're'],
        ['pattern' => 'ment'],
        ['pattern' => 'eur'],
        ['pattern' => 'euse'],
    ],
    'es' => [
        // Spanische Trennungsmuster
        ['pattern' => 'ch'],
        ['pattern' => 'll'],
        ['pattern' => 'rr'],
        ['pattern' => 'ción'],
        ['pattern' => 'pre'],
        ['pattern' => 'des'],
        ['pattern' => 'mente'],
        ['pattern' => 'dad'],
        ['pattern' => 'idad'],
    ],
    'it' => [
        // Italienische Trennungsmuster
        ['pattern' => 'ch'],
        ['pattern' => 'gh'],
        ['pattern' => 'gl'],
        ['pattern' => 'gn'],
        ['pattern' => 'sc'],
        ['pattern' => 'zione'],
        ['pattern' => 'pre'],
        ['pattern' => 'in'],
        ['pattern' => 'con'],
        ['pattern' => 'mente'],
    ],
    'nl' => [
        // Niederländische Trennungsmuster
        ['pattern' => 'sch'],
        ['pattern' => 'ch'],
        ['pattern' => 'ij'],
        ['pattern' => 'ing'],
        ['pattern' => 'ver'],
        ['pattern' => 'ont'],
        ['pattern' => 'be'],
        ['pattern' => 'ge'],
        ['pattern' => 'heid'],
        ['pattern' => 'lijk'],
    ],
    'pt' => [
        // Portugiesische Trennungsmuster
        ['pattern' => 'ch'],
        ['pattern' => 'lh'],
        ['pattern' => 'nh'],
        ['pattern' => 'ção'],
        ['pattern' => 'pre'],
        ['pattern' => 'des'],
        ['pattern' => 'mente'],
        ['pattern' => 'dade'],
        ['pattern' => 'idade'],
    ],
    'zh' => [
        // Chinesische Trennungsmuster (einfache Beispiele)
        ['pattern' => '的'],
        ['pattern' => '是'],
        ['pattern' => '在'],
        ['pattern' => '有'],
        ['pattern' => '和'],
    ],
    'ar' => [
        // Arabische Trennungsmuster (einfache Beispiele)
        ['pattern' => 'ال'],
        ['pattern' => 'في'],
        ['pattern' => 'من'],
        ['pattern' => 'على'],
        ['pattern' => 'إلى'],
    ],
    'hi' => [
        // Hindi Trennungsmuster (einfache Beispiele)
        ['pattern' => 'का'],
        ['pattern' => 'की'],
        ['pattern' => 'के'],
        ['pattern' => 'में'],
        ['pattern' => 'है'],
    ],
];
